export const REQUEST_ORDERS_BY_OWNER = 'REQUEST_ORDERS_BY_OWNER'
export const REQUEST_ORDERS_BY_OWNER_SUCCESS = 'REQUEST_ORDERS_BY_OWNER_SUCCESS'
export const REQUEST_ORDERS_BY_OWNER_ERROR = 'REQUEST_ORDERS_BY_OWNER_SUCCESS'

export const REQUEST_ORDERS_BY_USER = 'REQUEST_ORDERS_BY_USER'
export const REQUEST_ORDERS_BY_USER_SUCCESS = 'REQUEST_ORDERS_BY_USER_SUCCESS'
export const REQUEST_ORDERS_BY_USER_ERROR = 'REQUEST_ORDERS_BY_USER_SUCCESS'

export const CREATE_ORDER = 'CREATE_ORDER'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'
